### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by Kerwin1202** [ParaParty/OneBot-CommandRoute-Template#2]
上面configbot 里`startservice`过一次了
![image](https://user-images.githubusercontent.com/16319833/150259411-7af92103-3051-4076-9467-b0f1ed2005b4.png)

**Comment by ExerciseBook** [comment]
抱歉，我的锅，我检查一下。

**Comment by ExerciseBook** [comment]
诶，我查了一下。出现这个问题一个可能的原因是核心依赖你用的是 dev-main 分支。那个版本我还没发布。


我要在我这边跑一段时间没问题了我才敢发。

**Comment by Kerwin1202** [comment]
看了下确实是的，我是因为 https://github.com/ParaParty/OneBot-Framework/issues/10#issue-1108349643  这个问题 所以直接改了Sora 源码 直接引用两个项目源码了

**Comment by ExerciseBook** [comment]
ok~ 没事了就好。

**Comment by ExerciseBook** [comment]
https://github.com/ParaParty/OneBot-Framework/commit/bede517c2ea18879d730081593d775e2f2581dd5
在这个 Commit 中，改为了让 ASP.NET 来管理 sora 启动了。感觉会更优雅一点。
